services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    args:
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
  storybook:
    build:
      context: .
      dockerfile: ./apps/storybook/Dockerfile
    restart: always
    ports:
      - '6006:80'