services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_INTERNAL_API_URL: ${NEXT_PUBLIC_INTERNAL_API_URL}
    restart: always
    ports:
      - '3000:3000'
  storybook:
    build:
      context: .
      dockerfile: ./apps/storybook/Dockerfile
    restart: always
    ports:
      - '6006:80'