import type { Metadata } from 'next'
import { Onest } from 'next/font/google'

import { Providers } from '~/app/providers'
import { AppChildren } from '~/types'

import '~/app/globals.css'

const base = Onest({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '100', '200', '300', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: Readonly<AppChildren>) => {
  return (
    <html lang="en">
      <body className={base.className.concat(' antialiased')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
