import clsx from 'clsx'
import type { Metadata } from 'next'
import { Sour_Gummy } from 'next/font/google'

import { AppChildren } from '~/types'

import '~/app/globals.css'

const base = Sour_Gummy({
  subsets: ['latin'],
  weight: ['400']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: Readonly<AppChildren>) => {
  return (
    <html lang="en">
      <body className={clsx(base.className, 'antialiased')}>{children}</body>
    </html>
  )
}

export default RootLayout
